language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t sudhakar914/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sudhakar914/docker-react npm run test